#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("myMenu2.Resource", IsApplication=true)]

namespace myMenu2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int book = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int electoronics = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int frame_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frame_style2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int frame_style3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GAME = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int googleg_standard = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hoken = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Kankon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maru_btn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int movie = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int reform = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shopping = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int SxL_s1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Travel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Warranty = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int WOODHOUSE = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int yamada_icon = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int Image = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int NameText = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int RightArrow = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int appBtn1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int appBtn2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int appBtn3 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int appBtn4 = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int appNumber = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int centerBtn = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int centerLayout = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int dateText = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int google_play = 2131099651;
			
			// aapt resource value: 0x7f060032
			public const int item1 = 2131099698;
			
			// aapt resource value: 0x7f06003b
			public const int item10 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int item11 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int item12 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int item13 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int item14 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int item15 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int item16 = 2131099713;
			
			// aapt resource value: 0x7f060033
			public const int item2 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int item3 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int item4 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int item5 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int item6 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int item7 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int item8 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int item9 = 2131099706;
			
			// aapt resource value: 0x7f060009
			public const int labelText = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int listView1 = 2131099652;
			
			// aapt resource value: 0x7f060023
			public const int numBtn0 = 2131099683;
			
			// aapt resource value: 0x7f060019
			public const int numBtn1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int numBtn2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int numBtn3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int numBtn4 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int numBtn5 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int numBtn6 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int numBtn7 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int numBtn8 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int numBtn9 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int numBtnAsta = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int numBtnSharp = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int option_menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int pict_change = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int relativeLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int tenKeyGrid = 2131099672;
			
			// aapt resource value: 0x7f060025
			public const int tenKeyMoji = 2131099685;
			
			// aapt resource value: 0x7f060017
			public const int tenkeyLayout = 2131099671;
			
			// aapt resource value: 0x7f060030
			public const int textView0 = 2131099696;
			
			// aapt resource value: 0x7f060026
			public const int textView1 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int textView2 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int textView3 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int textView4 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int textView5 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int textView6 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int textView7 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int textView8 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int textView9 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int textViewAsta = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int textViewSharp = 2131099697;
			
			// aapt resource value: 0x7f060000
			public const int title_icon = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int upperLayout = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int weatherText1 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int weatherText2 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int webView1 = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int yearText = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_apps_list = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ListItemRow = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int popup_menu = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
